
import { Category, Post, AdConfig } from './types';

export const INITIAL_POSTS: Post[] = [
  {
    id: '1',
    title: 'Why You’re Still Tired After a Full Night’s Sleep',
    slug: 'why-still-tired-after-full-sleep',
    summary: 'Waking up exhausted despite getting eight hours of rest is a common frustration. Discover the difference between sleep quantity and quality.',
    content: `<h2>The Quality vs. Quantity Paradox</h2><p>We’ve been told since childhood that eight hours is the "magic number." Yet, many of us wake up feeling like we’ve barely closed our eyes. This phenomenon, often called 'non-restorative sleep,' suggests that while you are unconscious, your brain isn't successfully navigating the necessary cycles of repair.</p><h3>1. Sleep Fragmentation</h3><p>Even if you don't remember waking up, your brain might be experiencing micro-arousals. These can be caused by ambient noise, a partner moving, or mild sleep apnea. Each "ping" pulls you out of deep sleep, resetting the clock on your recovery.</p><h3>2. The Role of Sleep Hygiene</h3><p>Your body is a finely tuned machine. If you consume caffeine late in the day or use high-intensity blue light screens before bed, your brain may be "sleeping" but your nervous system is still wired, preventing the transition into Stage 3 REM sleep.</p>`,
    category: Category.RECOVERY,
    author: 'Dr. Helena Vance',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1541781719117-a23a4a158ec2?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Why Am I Still Tired After 8 Hours? | DeepRest Journal',
    metaDescription: 'Explore the hidden reasons why you wake up exhausted even after a full night of sleep. Learn about sleep quality, fragmentation, and recovery.',
    keywords: ['tired after sleep', 'non-restorative sleep', 'sleep quality', 'exhaustion'],
    canonicalUrl: 'https://deeprestjournal.com/why-still-tired-after-full-sleep',
    altText: 'A woman sitting up in bed looking exhausted despite it being morning.'
  },
  {
    id: '2',
    title: 'Night Anxiety: Why Your Mind Gets Louder When the Lights Go Off',
    slug: 'night-anxiety-mind-louder-at-night',
    summary: 'The sun goes down and the volume of your thoughts goes up. Understand the science of nocturnal worry and how to silence it.',
    content: `<h2>The Midnight Echo Chamber</h2><p>During the day, we are surrounded by distractions—work, family, entertainment, and social interaction. When we lie in bed, those distractions disappear, leaving us alone with our thoughts. For those with anxiety, this silence acts as a megaphone for every "what if" and "I should have" that was ignored during the day.</p><h3>The Biological Component</h3><p>As evening progresses, our cortisol levels (the stress hormone) should naturally drop. However, if you are chronically stressed, these levels may remain elevated or spike at odd hours, triggering a "fight or flight" response while you are trying to rest.</p><h3>Breaking the Silence</h3><p>Cognitive Behavioral Therapy for Insomnia (CBT-I) suggests 'Scheduled Worry Time' during the day. By giving your worries a dedicated 15 minutes at 4:00 PM, you train your brain that 11:00 PM is not the time for problem-solving.</p>`,
    category: Category.ANXIETY,
    author: 'Julian Thorne, PsyD',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Night Anxiety: Why Your Mind Races at Bedtime',
    metaDescription: 'Understand why anxiety peaks at night and learn psychological strategies to calm your racing mind before sleep.',
    keywords: ['night anxiety', 'racing thoughts', 'bedtime worry', 'insomnia anxiety'],
    canonicalUrl: 'https://deeprestjournal.com/night-anxiety-mind-louder-at-night',
    altText: 'A person staring at the ceiling in a dark room.'
  },
  {
    id: '3',
    title: 'The Hidden Link Between Chronic Stress and Poor Sleep',
    slug: 'chronic-stress-and-poor-sleep-link',
    summary: 'Stress isn’t just a feeling; it’s a physiological state that actively blocks sleep. Learn how the HPA axis governs your nights.',
    content: `<h2>The Stress-Sleep Cycle</h2><p>Chronic stress creates a biological environment that is hostile to sleep. When the body perceives a threat—even if it's just a mountain of emails—it activates the Hypothalamic-Pituitary-Adrenal (HPA) axis.</p><h3>Vigilance vs. Vulnerability</h3><p>Sleep is a vulnerable state. From an evolutionary perspective, our ancestors couldn't afford to sleep deeply if a predator was near. Modern stress signals to our primitive brain that a "predator" is nearby, keeping us in a state of hyper-vigilance.</p><h3>Restoring Balance</h3><p>Vagus nerve stimulation, through deep breathing and cold exposure, can help "flip the switch" from the sympathetic (fight/flight) to the parasympathetic (rest/digest) nervous system.</p>`,
    category: Category.INSOMNIA,
    author: 'Dr. Sarah Mitchell',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1484417894907-623942c8ee29?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Chronic Stress and Sleep Loss: Breaking the Cycle',
    metaDescription: 'Discover how chronic stress impacts your HPA axis and prevents restorative sleep. Strategies for stress-induced insomnia.',
    keywords: ['stress and sleep', 'cortisol', 'HPA axis', 'restorative rest'],
    canonicalUrl: 'https://deeprestjournal.com/chronic-stress-and-poor-sleep-link',
    altText: 'Stressed professional leaning head on hands in front of a laptop.'
  },
  {
    id: '4',
    title: 'Sleep Debt Explained: How Missed Sleep Affects Your Brain and Body',
    slug: 'sleep-debt-explained-brain-body-effects',
    summary: 'You can’t simply "catch up" on sleep over the weekend. Understand the compounding interest of sleep deprivation.',
    content: `<h2>The Myth of Weekend Recovery</h2><p>Sleep debt is cumulative. If you need 8 hours but only get 6 for five nights, you have a 10-hour debt by Saturday morning. Research shows that while you might feel more alert after a long Saturday nap, your cognitive performance—specifically focus and reaction time—remains degraded.</p><h3>Cognitive Decline</h3><p>Operating on 4 hours of sleep for three nights in a row is metabolically equivalent to having a Blood Alcohol Concentration (BAC) of 0.05%. Your brain’s ability to clear metabolic waste through the glymphatic system is severely hampered.</p>`,
    category: Category.CLARITY,
    author: 'Prof. Marcus Chen',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9eaa37a11944?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'What is Sleep Debt? Impacts on Cognitive Health',
    metaDescription: 'Learn about the compounding effects of sleep debt on your brain and why weekend sleep marathons don’t fix the problem.',
    keywords: ['sleep debt', 'brain health', 'sleep deprivation', 'recovery'],
    canonicalUrl: 'https://deeprestjournal.com/sleep-debt-explained-brain-body-effects',
    altText: 'A conceptual image of a battery running low.'
  },
  {
    id: '5',
    title: 'How Work Stress Silently Destroys Sleep Quality',
    slug: 'work-stress-destroys-sleep-quality',
    summary: 'For the modern professional, work doesn’t end when the laptop closes. It follows you into your dreams.',
    content: `<h2>The Boundary Problem</h2><p>In the age of remote work and constant connectivity, the physical and temporal boundaries between "office" and "home" have vanished. This lack of transition prevents the brain from entering the pre-sleep "wind-down" phase.</p><h3>Professional Hyperarousal</h3><p>Anticipating the next day's tasks or replaying a difficult meeting creates a state of mental hyperarousal. This doesn't just keep you awake; it reduces the time spent in slow-wave sleep, the stage where physical tissues and memory are repaired.</p>`,
    category: Category.HYGIENE,
    author: 'Emma Sterling',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Work Stress and Sleep: Strategies for Professionals',
    metaDescription: 'Is work keeping you awake? Learn how professional stress impacts sleep architecture and how to set boundaries for rest.',
    keywords: ['work stress', 'professional sleep', 'boundaries', 'productivity'],
    canonicalUrl: 'https://deeprestjournal.com/work-stress-destroys-sleep-quality',
    altText: 'People in a high-pressure office environment.'
  },
  {
    id: '6',
    title: 'Overthinking at Night: How to Calm a Racing Mind Before Bed',
    slug: 'overthinking-at-night-calm-racing-mind',
    summary: 'Practical, evidence-based techniques to stop the late-night loop of intrusive thoughts.',
    content: `<h2>The Science of Rumination</h2><p>Rumination is the act of focused attention on the symptoms of one's distress. At night, without external input, the brain defaults to its "Task Positive Network" or "Default Mode Network," often dwelling on unresolved problems.</p><h3>The "Brain Dump" Technique</h3><p>Keep a notebook by your bed. If a thought keeps looping, write it down. The act of externalizing the thought tells the brain: "This information is safely stored elsewhere; you no longer need to hold it in active memory."</p>`,
    category: Category.ANXIETY,
    author: 'Dr. Julian Reed',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1444464666168-49d633b86747?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'How to Stop Overthinking Before Bed | DeepRest',
    metaDescription: 'Master the art of calming your mind at night. Proven techniques to end rumination and fall asleep faster.',
    keywords: ['overthinking', 'calm mind', 'bedtime routine', 'anxiety'],
    canonicalUrl: 'https://deeprestjournal.com/overthinking-at-night-calm-racing-mind',
    altText: 'A person writing in a journal by candlelight.'
  },
  {
    id: '7',
    title: 'The Science of Deep Sleep and Why You Rarely Get Enough of It',
    slug: 'science-of-deep-sleep-missing-rest',
    summary: 'Deep sleep is the "power wash" for your brain. Discover why modern life is robbing you of this critical stage.',
    content: `<h2>What Happens in Stage 3?</h2><p>During deep sleep, your heart rate and breathing drop to their lowest levels. Your brain waves slow into large, rhythmic 'delta waves.' This is when growth hormone is released, and your immune system strengthens.</p><h3>The Enemy: Alcohol and Temperature</h3><p>Even a single drink can reduce deep sleep significantly. Alcohol is a sedative, not a sleep aid; it induces unconsciousness while bypassing the deep, restorative stages. Similarly, a warm room prevents the necessary drop in core body temperature required for Stage 3.</p>`,
    category: Category.RECOVERY,
    author: 'Dr. Helena Vance',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1541480601022-23057d16a38c?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'How to Increase Deep Sleep Naturally',
    metaDescription: 'Deep sleep is essential for physical and mental health. Learn the science behind Stage 3 sleep and how to optimize it.',
    keywords: ['deep sleep', 'REM sleep', 'recovery', 'sleep stages'],
    canonicalUrl: 'https://deeprestjournal.com/science-of-deep-sleep-missing-rest',
    altText: 'A macro view of a sleeping person’s face.'
  },
  {
    id: '8',
    title: 'Why Parents Are Always Exhausted—Even When the Kids Sleep',
    slug: 'why-parents-exhausted-even-when-kids-sleep',
    summary: 'Parental burnout isn’t just about the kids waking up at night. It’s the "vigilance fatigue" that remains.',
    content: `<h2>The Vigilance Fatigue</h2><p>New parents develop a heightened sensitivity to noise. This 'vigilance' doesn't disappear just because the child is now sleeping through the night. The brain remains in a "wait-and-listen" state, preventing the transition into deep rest.</p><h3>The Invisible Load</h3><p>The mental load of parenting—scheduling, emotional regulation, and constant multitasking—keeps the brain in a high-arousal state all day. When nighttime comes, the system cannot simply shut off.</p>`,
    category: Category.RECOVERY,
    author: 'Sarah Jenkins, M.Ed',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1502086223501-7ea244391501?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Parental Exhaustion: Beyond the Lack of Sleep',
    metaDescription: 'Parents often feel tired even when their children sleep. Discover the concept of vigilance fatigue and mental load.',
    keywords: ['parenting exhaustion', 'mom fatigue', 'dad tired', 'sleep training'],
    canonicalUrl: 'https://deeprestjournal.com/why-parents-exhausted-even-when-kids-sleep',
    altText: 'A mother resting her head on a kitchen counter.'
  },
  {
    id: '9',
    title: 'Phone Scrolling Before Bed: How It Steals Rest Without You Noticing',
    slug: 'phone-scrolling-steals-rest-bedtime',
    summary: 'The "just five more minutes" loop is more dangerous for your brain than you think.',
    content: `<h2>Dopamine vs. Melatonin</h2><p>Scrolling through social media or news feeds does two things: it exposes you to blue light, which suppresses melatonin, and it provides hits of dopamine, which signals to the brain that it's time to be alert and seek rewards.</p><h3>The "Revenge Bedtime Procrastination"</h3><p>Many busy professionals feel they have no control over their daytime hours, so they "steal" time at night by scrolling. This psychological phenomenon is a form of self-sabotage that trades long-term health for short-term control.</p>`,
    category: Category.HYGIENE,
    author: 'Tech-Health Editor',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1520110120835-c96534a4c984?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Stop Scrolling Before Bed: The Sleep Thief',
    metaDescription: 'Is your phone stealing your sleep? Learn how blue light and dopamine scrolling destroy your rest quality.',
    keywords: ['blue light', 'phone at night', 'scrolling', 'melatonin'],
    canonicalUrl: 'https://deeprestjournal.com/phone-scrolling-steals-rest-bedtime',
    altText: 'A blue glow from a smartphone lighting up a person’s face in the dark.'
  },
  {
    id: '10',
    title: 'Insomnia Isn’t Laziness: Understanding the Real Causes of Sleeplessness',
    slug: 'insomnia-not-laziness-real-causes',
    summary: 'Shifting the narrative around insomnia from a character flaw to a complex physiological condition.',
    content: `<h2>Debunking the Myth</h2><p>There is a pervasive social stigma that people who can't sleep are simply "not trying hard enough" or are "lazy." In reality, insomnia is often a state of chronic hyperarousal where the brain's "on" switch is jammed.</p><h3>Genetics and Biology</h3><p>Some people are genetically predisposed to being 'short sleepers' or have a delayed sleep phase. Understanding your biological clock (chronotype) is the first step in treating insomnia with compassion rather than guilt.</p>`,
    category: Category.INSOMNIA,
    author: 'Dr. Sarah Mitchell',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1541480601022-23057d16a38c?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Understanding the Real Causes of Insomnia',
    metaDescription: 'Insomnia is a complex condition, not a sign of laziness. Learn about hyperarousal and biological causes of sleeplessness.',
    keywords: ['insomnia causes', 'sleeplessness', 'sleep health', 'mental health'],
    canonicalUrl: 'https://deeprestjournal.com/insomnia-not-laziness-real-causes',
    altText: 'An empty bed with rumpled sheets.'
  },
  {
    id: '11',
    title: 'How Poor Sleep Affects Memory, Focus, and Decision-Making',
    slug: 'poor-sleep-affects-memory-focus',
    summary: 'Your brain needs sleep to "save" what you learned today. Without it, you are effectively running on a failing hard drive.',
    content: `<h2>Memory Consolidation</h2><p>During REM sleep, the hippocampus and neocortex communicate to move information from short-term to long-term storage. If you skip this, new information is simply lost.</p><h3>Prefrontal Cortex Impairment</h3><p>The prefrontal cortex is responsible for executive function. Sleep deprivation causes this area to go "offline," leading to poor impulse control, irritability, and an inability to focus on complex tasks.</p>`,
    category: Category.CLARITY,
    author: 'Prof. Marcus Chen',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Sleep and Cognitive Performance: The Connection',
    metaDescription: 'Learn how sleep deprivation impacts memory, focus, and decision-making. Protect your cognitive health with rest.',
    keywords: ['memory', 'focus', 'cognition', 'decision making'],
    canonicalUrl: 'https://deeprestjournal.com/poor-sleep-affects-memory-focus',
    altText: 'A conceptual image of gears turning in a brain.'
  },
  {
    id: '12',
    title: 'Morning Brain Fog: Causes, Signs, and How to Fix It Naturally',
    slug: 'morning-brain-fog-causes-fixes',
    summary: 'That groggy, confused feeling upon waking has a name: Sleep Inertia. Learn how to shake it off.',
    content: `<h2>What is Sleep Inertia?</h2><p>Sleep inertia is the transitional state between sleep and wakefulness, marked by impaired performance and a desire to return to sleep. It usually lasts 15-30 minutes, but for some, it can linger for hours.</p><h3>Fixing the Fog</h3><p>Exposure to bright morning sunlight is the fastest way to signal to your brain to stop producing melatonin and start producing cortisol and serotonin. Hydration is also key, as your brain is naturally dehydrated after 8 hours of rest.</p>`,
    category: Category.CLARITY,
    author: 'Dr. Helena Vance',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'How to Cure Morning Brain Fog Naturally',
    metaDescription: 'Struggling to wake up? Discover the causes of sleep inertia and natural ways to clear your morning brain fog.',
    keywords: ['brain fog', 'sleep inertia', 'morning energy', 'clarity'],
    canonicalUrl: 'https://deeprestjournal.com/morning-brain-fog-causes-fixes',
    altText: 'Sunlight streaming into a bedroom window.'
  },
  {
    id: '13',
    title: 'Why Emotional Stress Shows Show Up as Physical Exhaustion',
    slug: 'emotional-stress-physical-exhaustion',
    summary: 'The mind-body connection is never more apparent than when heartbreak or worry feels like a physical weight.',
    content: `<h2>The Burden of Feeling</h2><p>Emotional labor—processing grief, managing social anxiety, or dealing with conflict—consumes an enormous amount of metabolic energy. Your brain uses about 20% of your body's calories, and intense emotion can spike that usage.</p><h3>The Somatic Connection</h3><p>When the brain is overtaxed, it sends signals to the body to slow down. This manifests as muscle aches, heavy limbs, and a general lack of physical vitality. Rest, in this case, needs to be both mental and physical.</p>`,
    category: Category.RECOVERY,
    author: 'Julian Thorne, PsyD',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1474418397713-7ded8140f4cb?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Emotional Stress and Physical Fatigue: The Link',
    metaDescription: 'Why does stress feel so physically tiring? Explore the somatic side of emotional exhaustion and how to recover.',
    keywords: ['emotional stress', 'physical exhaustion', 'somatic', 'fatigue'],
    canonicalUrl: 'https://deeprestjournal.com/emotional-stress-physical-exhaustion',
    altText: 'A lone person sitting on a bench in the fog.'
  },
  {
    id: '14',
    title: 'Can Sleep Reduce Anxiety? What Science Actually Says',
    slug: 'can-sleep-reduce-anxiety-science',
    summary: 'Sleep isn’t just a passive state; it’s an active neurological therapy for the anxious brain.',
    content: `<h2>The Overnight Therapy</h2><p>During REM sleep, the amygdala (the brain's fear center) is "reset." This allows us to process difficult emotions without the associated stress response. Research shows that one night of total sleep deprivation can increase anxiety levels by up to 30%.</p><h3>A Bidirectional Relationship</h3><p>By prioritizing sleep, you are giving your brain the tools it needs to regulate emotion. Good sleep acts as a "buffer" against the stressors of the next day.</p>`,
    category: Category.ANXIETY,
    author: 'Dr. Sarah Mitchell',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1469474094887-11830a50bc74?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Does Sleep Help Anxiety? The Science Explained',
    metaDescription: 'Discover the therapeutic power of REM sleep in regulating anxiety and managing stress levels.',
    keywords: ['anxiety relief', 'sleep therapy', 'REM sleep', 'mental health'],
    canonicalUrl: 'https://deeprestjournal.com/can-sleep-reduce-anxiety-science',
    altText: 'A peaceful nature scene with a calm lake.'
  },
  {
    id: '15',
    title: 'Burnout and Sleep: Why Rest Is the First Step to Recovery',
    slug: 'burnout-recovery-first-step-rest',
    summary: 'You can’t "hustle" your way out of burnout. You have to sleep your way out.',
    content: `<h2>The Burnout Cycle</h2><p>Burnout is a state of emotional, physical, and mental exhaustion caused by excessive and prolonged stress. It occurs when you feel overwhelmed, emotionally drained, and unable to meet constant demands.</p><h3>Restorative Recovery</h3><p>True recovery from burnout starts with radical rest. This means guilt-free sleep, removing high-arousal stimuli, and allowing the nervous system to return to its baseline.</p>`,
    category: Category.RECOVERY,
    author: 'Emma Sterling',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Recovering from Burnout: The Role of Sleep',
    metaDescription: 'Burnout requires more than just a vacation. Learn why restorative sleep is the foundation of burnout recovery.',
    keywords: ['burnout', 'recovery', 'rest', 'wellbeing'],
    canonicalUrl: 'https://deeprestjournal.com/burnout-recovery-first-step-rest',
    altText: 'A person practicing yoga in a calm, sunny room.'
  },
  {
    id: '16',
    title: 'A Simple Night Routine That Actually Helps You Sleep Better',
    slug: 'simple-night-routine-sleep-better',
    summary: 'You don’t need a 2-hour ritual. Here is a 15-minute routine that signals your brain it’s time to sleep.',
    content: `<h2>The Power of Predictability</h2><p>Your brain loves cues. A consistent routine acts as a Pavlovian signal to start the wind-down process.</p><h3>The 15-Minute Protocol</h3><p>1. Dim the lights. 2. A quick 'brain dump' journal entry. 3. Three minutes of box breathing. These simple steps are often more effective than complex, stressful "self-care" rituals.</p>`,
    category: Category.HYGIENE,
    author: 'James Clear-Sleep',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1445510491599-c391e8046a68?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Best Bedtime Routine for Deep Rest',
    metaDescription: 'Create a simple, effective night routine to improve your sleep quality. Science-backed tips for a better night.',
    keywords: ['night routine', 'sleep habits', 'bedtime ritual', 'better sleep'],
    canonicalUrl: 'https://deeprestjournal.com/simple-night-routine-sleep-better',
    altText: 'A pair of slippers and a book on a bedside rug.'
  },
  {
    id: '17',
    title: 'Breathing Techniques That Calm the Nervous System Before Bed',
    slug: 'breathing-techniques-calm-nervous-system',
    summary: 'Your breath is the remote control for your nervous system. Learn how to use it.',
    content: `<h2>Vagus Nerve Activation</h2><p>By lengthening your exhales, you stimulate the vagus nerve, which tells your heart and brain to slow down.</p><h3>Box Breathing and 4-7-8</h3><p>The 4-7-8 technique—inhale for 4, hold for 7, exhale for 8—is specifically designed to lower heart rate and prepare the body for the paralytic state of sleep.</p>`,
    category: Category.ANXIETY,
    author: 'Dr. Julian Reed',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Breathing Exercises for Sleep and Anxiety',
    metaDescription: 'Learn box breathing and 4-7-8 techniques to calm your nervous system and fall asleep faster.',
    keywords: ['breathing', 'meditation', 'vagus nerve', 'relaxation'],
    canonicalUrl: 'https://deeprestjournal.com/breathing-techniques-calm-nervous-system',
    altText: 'Close up of someone meditating.'
  },
  {
    id: '18',
    title: 'Foods and Drinks That Secretly Ruin Your Sleep Quality',
    slug: 'foods-drinks-ruin-sleep-quality',
    summary: 'It’s not just caffeine. Discover the hidden sleep-disruptors in your diet.',
    content: `<h2>The Sugar Spike</h2><p>Late-night sugar consumption causes a glucose spike followed by a crash, which can trigger the release of cortisol, waking you up in the middle of the night.</p><h3>Hidden Caffeine</h3><p>Decaf coffee and dark chocolate still contain enough caffeine to disrupt sensitive sleepers. Even high-protein meals right before bed can interfere with the body's cooling process.</p>`,
    category: Category.HYGIENE,
    author: 'Nutrition-Health Editor',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Sleep-Disrupting Foods to Avoid at Night',
    metaDescription: 'Is your diet keeping you awake? Learn about the hidden caffeine and sugar in common nighttime snacks.',
    keywords: ['diet and sleep', 'nighttime snacks', 'sugar', 'caffeine'],
    canonicalUrl: 'https://deeprestjournal.com/foods-drinks-ruin-sleep-quality',
    altText: 'A variety of fresh foods on a wooden table.'
  },
  {
    id: '19',
    title: 'Weekend Catch-Up Sleep: Helpful or Harmful?',
    slug: 'weekend-catch-up-sleep-good-bad',
    summary: 'The "Social Jetlag" phenomenon explained: Why sleeping in on Sunday might make Monday harder.',
    content: `<h2>Social Jetlag</h2><p>When your weekday and weekend sleep schedules differ by more than two hours, you create a state similar to crossing multiple time zones. This disrupts your circadian rhythm, making it impossible for your body to know when to release melatonin.</p><h3>The Verdict</h3><p>An extra hour is fine, but a 4-hour "catch-up" session will leave you with a 'Monday morning hangover' of grogginess and low mood.</p>`,
    category: Category.HYGIENE,
    author: 'Dr. Helena Vance',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1541480601022-23057d16a38c?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'The Truth About Catching Up on Sleep',
    metaDescription: 'Does weekend sleep actually work? Learn about social jetlag and how to maintain a consistent sleep schedule.',
    keywords: ['catch up sleep', 'weekend sleep', 'social jetlag', 'circadian rhythm'],
    canonicalUrl: 'https://deeprestjournal.com/weekend-catch-up-sleep-good-bad',
    altText: 'A person sleeping comfortably on a Sunday morning.'
  },
  {
    id: '20',
    title: 'How to Train Your Body to Sleep Better Without Medication',
    slug: 'train-body-sleep-better-without-meds',
    summary: 'Building a sustainable, drug-free relationship with rest through behavioral conditioning.',
    content: `<h2>Stimulus Control</h2><p>Your brain should associate the bed only with sleep (and sex). If you work, watch TV, or worry in bed, you are conditioning your brain to be alert in that space.</p><h3>Light and Temperature</h3><p>Training your body means mastering your environment. 65 degrees and total darkness are the biological prerequisites for deep rest. Consistency is your greatest tool.</p>`,
    category: Category.INSOMNIA,
    author: 'Dr. Sarah Mitchell',
    date: new Date().toISOString(),
    imageUrl: 'https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?auto=format&fit=crop&q=80&w=1200',
    seoTitle: 'Natural Sleep Training for Adults',
    metaDescription: 'Improve your sleep without medication. Learn stimulus control and environmental optimization for better rest.',
    keywords: ['natural sleep', 'sleep training', 'insomnia treatment', 'no pills'],
    canonicalUrl: 'https://deeprestjournal.com/train-body-sleep-better-without-meds',
    altText: 'A calm bedroom with open curtains showing dawn.'
  }
];

export const INITIAL_ADS: AdConfig[] = [
  // Desktop / Web Ads
  { id: 'leaderboard-top', placement: 'Leaderboard – top of page', code: '<div class="bg-gray-100 h-24 flex items-center justify-center text-gray-400 border border-dashed border-gray-300 text-xs">DESKTOP LEADERBOARD (728x90)</div>', active: true },
  { id: 'anchor-bottom', placement: 'Anchor – bottom pinned banner', code: '<div class="bg-rose-600 text-white h-full flex items-center justify-center text-xs font-black uppercase tracking-widest">Premium Offer: Unlock 100% Deep Sleep Efficiency – Limited Time</div>', active: true },
  { id: 'sidebar-rect', placement: 'Medium Rectangle – sidebar', code: '<div class="bg-gray-100 h-64 flex items-center justify-center text-gray-400 border border-dashed border-gray-300 text-xs">SIDEBAR RECTANGLE (300x250)</div>', active: true },
  { id: 'in-article-rect', placement: 'Medium Rectangle – inside article', code: '<div class="bg-gray-50 h-64 flex items-center justify-center text-gray-400 border border-dashed border-gray-300 text-xs">IN-ARTICLE RECTANGLE</div>', active: true },
  { id: 'tenancy-rect', placement: 'Tenancy Rectangle', code: '<div class="bg-zinc-800 text-white h-48 flex items-center justify-center text-xs font-bold">EXCLUSIVE PARTNER TENANCY SPOT</div>', active: true },
  { id: 'in-text-banner', placement: 'In-text banners – inside content', code: '<div class="bg-rose-50 border-y border-rose-100 py-4 text-center text-rose-600 font-bold text-sm">SPONSORED: Discover the New Orthopedic Pillow Range</div>', active: true },
  { id: 'sticky-sidebar', placement: 'Sticky banners – scroll-stick', code: '<div class="bg-zinc-900 text-white h-96 flex items-center justify-center text-xs p-4 text-center italic">This banner follows your scroll for maximum exposure.</div>', active: true },
  { id: 'inter-article', placement: 'Inter-article banners', code: '<div class="bg-gray-100 py-8 px-4 text-center text-gray-500 border-y border-gray-200">INTER-ARTICLE NATIVE PLACEMENT</div>', active: true },
  { id: 'skyscraper', placement: 'Skyscraper – tall sidebar', code: '<div class="bg-gray-200 h-[600px] flex items-center justify-center text-gray-400 text-xs [writing-mode:vertical-lr] font-bold">TALL SKYSCRAPER AD (160x600)</div>', active: true },
  { id: 'in-stream-video', placement: 'In-stream video ads', code: '<div class="aspect-video bg-black flex items-center justify-center text-white text-xs">VIDEO AD PLAYER PLACEHOLDER</div>', active: true },
  { id: 'interstitial', placement: 'Interstitial full-screen ads', code: '<div class="fixed inset-0 bg-white z-[999] flex flex-col items-center justify-center p-8 text-center"><h2 class="text-3xl font-black mb-4">DeepRest Premium</h2><p class="mb-8">Experience the journal without limits.</p><button class="bg-rose-600 text-white px-8 py-3 rounded-full font-bold">SUBSCRIBE NOW</button></div>', active: false },
  { id: 'sponsorship-badge', placement: 'Sponsorship badge – for premium categories', code: '<span class="bg-amber-100 text-amber-700 px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-tighter ml-2">Sponsored by RestWell™</span>', active: true },

  // Mobile-Specific Placements
  { id: 'mobile-leaderboard', placement: 'Mobile Leaderboard', code: '<div class="bg-gray-100 h-16 flex items-center justify-center text-gray-400 border border-dashed border-gray-300 text-[10px]">MOBILE LEADERBOARD (320x50)</div>', active: true },
  { id: 'mobile-tenancy', placement: 'Mobile Tenancy Rectangle', code: '<div class="bg-zinc-800 text-white h-32 flex items-center justify-center text-[10px] font-bold">MOBILE TENANCY</div>', active: true },
  { id: 'mobile-in-text', placement: 'Mobile In-text', code: '<div class="bg-rose-50 border-y border-rose-100 py-3 text-center text-rose-600 font-bold text-xs">MOBILE SPONSORED CONTENT</div>', active: true },
  { id: 'mobile-anchor', placement: 'Mobile Anchor', code: '<div class="bg-zinc-900 text-white h-full flex items-center justify-center text-[10px] font-bold uppercase tracking-widest px-4">Daily Sleep Tip: Darken your room 1 hour before bed.</div>', active: true },
  { id: 'mobile-inter-article', placement: 'Mobile Inter-article', code: '<div class="bg-gray-50 py-4 px-2 text-center text-gray-400 text-[10px] border-y border-gray-100">MOBILE INTER-ARTICLE</div>', active: true },
  { id: 'mobile-in-stream-video', placement: 'Mobile in-stream video ads', code: '<div class="aspect-video bg-black flex items-center justify-center text-white text-[10px]">MOBILE VIDEO AD</div>', active: true }
];
